name: contacts_service_fork
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.6.3.1
homepage: https://github.com/lukasgit/flutter_contacts
maintainer: Lukas Dickie (@lukasgit)

environment:
  sdk: '^3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  quiver: ^3.2.2

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.contactsservice.contactsservice
        pluginClass: ContactsServicePlugin
      ios:
        pluginClass: ContactsServicePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.2
